//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSBitcoinDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class WaletImportFile
    {
        public int WifId { get; set; }
        public string Wif { get; set; }
        public string Name { get; set; }
    }
}
